name: express_delivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  # GetX
  get: 4.6.1
  get_storage: ^2.0.3
  ###

  flutter:
    sdk: flutter

  # utils
  logger: ^1.1.0
  intl: ^0.17.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.2
  json_annotation: ^4.0.1
  tuple: ^2.0.0
  blurhash: ^1.0.0
  flutter_blurhash: ^0.6.4
  flutter_svg: ^1.0.3
  timezone: ^0.8.0
  timeago: ^3.2.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  flutter_native_splash: ^2.1.2
  scrolls_to_top: ^1.1.1
  font_awesome_flutter: ^10.1.0
  path_provider: ^2.0.9
  flutter_native_image: ^0.0.6+1
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.0
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5
  dotted_line: ^3.1.0
  map_launcher: ^2.2.1+2
  ###

  #Animation
  animations: ^2.0.2
  ###

  ### lottie:
  lottie: ^1.2.2
  ###

  # service
  dio: ^4.0.5
  ###

  #Geo
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  ###

  # Google map
  google_maps_flutter: ^2.1.3
  ###

  #Syncfusion
  syncfusion_flutter_sliders: ^19.4.43
  syncfusion_flutter_charts: ^19.4.47
  syncfusion_flutter_core: ^19.4.43
  syncfusion_flutter_datepicker: ^19.4.43
  ###

  #animations list
  flutter_staggered_animations: "^1.0.0"
  #

  #firebase
  firebase_messaging: ^11.2.12
  firebase_core: ^1.14.0
  ###

  #socket io
  socket_io_client: ^2.0.0-beta.2
  ###

  # notification
  flutter_local_notifications: ^9.4.0
  ###

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  #Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/

#Flutter gen - image widget gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
###

